import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

export default function FAQ() {
  const faqs = [
    { q: "What is PM Surya Ghar: Muft Bijli Yojana?", a: "It's a central government scheme providing up to ₹78,000 subsidy for residential solar installations (up to 3kW) and aims to provide 300 units of free electricity per month." },
    { q: "How much roof space is required for a solar plant?", a: "Generally, you need about 100 sq. ft. of shade-free roof space per 1 kW of solar installation." },
    { q: "What is the lifespan of the solar panels?", a: "Tier-1 solar panels come with a 25-year performance warranty and can easily last 25-30 years with minimal maintenance." },
    { q: "How does net-metering work in Rajasthan?", a: "Net-metering allows you to export excess electricity generated by your solar plant back to the DISCOM grid. You are billed only for the 'net' energy you consume from the grid minus what you exported." },
    { q: "Do you help with the government subsidy process?", a: "Yes, we provide end-to-end assistance with the PM Surya Ghar Yojana portal, application, documentation, and final inspection to ensure you receive your subsidy directly in your bank account." },
    { q: "Is maintenance required for solar panels?", a: "Solar panels require very little maintenance. Periodic cleaning with water to remove dust every 15-30 days is usually sufficient to maintain optimal generation." },
    { q: "Do solar panels generate electricity during cloudy days or rain?", a: "Yes, they still generate electricity during cloudy days, though the efficiency might drop. They do not generate power at night." },
    { q: "How long does the installation process take?", a: "The physical installation takes 1-3 days. However, the complete process including DISCOM approvals and net-metering can take 3-4 weeks." },
    { q: "What happens during a power cut?", a: "In standard On-Grid systems, the inverter will automatically shut down during a power cut for safety reasons (anti-islanding). If you have frequent power cuts, we recommend a Hybrid system with battery backup." },
    { q: "Can solar panels withstand heavy wind and hail?", a: "Yes. We use high-grade mounting structures and Tier-1 panels with tempered glass tested to withstand heavy winds and standard hail impacts." },
  ];

  const [open, setOpen] = useState<number | null>(0);

  return (
    <section id="faq" className="py-24 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-sm font-bold text-emerald-700 tracking-widest uppercase mb-3">FAQ</h2>
          <h3 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Frequently Asked Questions</h3>
          <p className="text-slate-600 max-w-2xl mx-auto text-lg">Got questions? We've got answers. If you don't see your question here, feel free to contact us.</p>
        </div>
        
        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <div key={i} className="border border-slate-200 rounded-2xl overflow-hidden transition-all duration-300 hover:border-emerald-200 bg-white">
              <button 
                className="w-full px-6 py-5 text-left flex justify-between items-center focus:outline-none"
                onClick={() => setOpen(open === i ? null : i)}
                aria-expanded={open === i}
              >
                <span className="font-semibold text-slate-900 pr-8 text-lg">{faq.q}</span>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-colors ${open === i ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-50 text-slate-500'}`}>
                  <ChevronDown className={`w-5 h-5 transition-transform duration-300 ${open === i ? 'rotate-180' : ''}`} />
                </div>
              </button>
              <div 
                className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${open === i ? 'max-h-96 pb-6 opacity-100' : 'max-h-0 opacity-0'}`}
              >
                <p className="text-slate-600 leading-relaxed text-base pt-2 border-t border-slate-100">
                  {faq.a}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
